/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import conexiones.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carreto
 */
public class frmMICRUD extends javax.swing.JFrame {
      conexionSQL cc= new conexionSQL ();
        Connection cn = cc.conexionSQL();
   

    /**
     * Creates new form frmMICRUD
     */
    public frmMICRUD() {
        initComponents();
          MostrarDatos ();
        lblMensaje.setText("contructor sin parametros");
      
     }
       public frmMICRUD  (String  lblMensaje)
       {
            initComponents();
           this.lblMensaje.setText(lblMensaje);
           
       }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCalificacion = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMensaje.setText("Prueba constructor");

        jLabel1.setText("Nombre del Alumno:");

        jLabel2.setText("Apellido del Alumno:");

        jLabel3.setText("Curso:");

        jLabel4.setText("Calificacion:");

        txtCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCalificacionActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton4.setText("Nuevo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAlumnosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAlumnos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar)))
                        .addGap(34, 34, 34)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(178, 178, 178)
                                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMensaje))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar)
                            .addComponent(jButton4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
  
                       insertarDatos();  
         MostrarDatos ();   
                    
                      
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        nuevo ();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
          
        editar ();
          MostrarDatos ();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jTableAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAlumnosMouseClicked
        // TODO add your handling code here:
        int filaSelect = jTableAlumnos.rowAtPoint(evt.getPoint());
        txtNombre.setText(jTableAlumnos.getValueAt(filaSelect, 1).toString());
        
        txtApellido.setText(jTableAlumnos.getValueAt(filaSelect, 2).toString());
        
        txtCurso.setText(jTableAlumnos.getValueAt(filaSelect, 3).toString());
        
        txtCalificacion.setText(jTableAlumnos.getValueAt(filaSelect, 4).toString());
    }//GEN-LAST:event_jTableAlumnosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminar ();
         MostrarDatos ();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCalificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCalificacionActionPerformed

             public void insertarDatos (){
            try
            {
                
            
                String sSql="insert into alumnos (nombre,apeliido,materia,calificacion) values (?,?,?,?)";
                
                  PreparedStatement p = cn.prepareStatement(sSql);
                  p.setString(1, txtNombre.getText());
                  p.setString(2, txtApellido.getText());
                  p.setString(3, txtCurso.getText());
                  p.setString(4, txtCalificacion.getText());
                  String home = txtCalificacion.getText();
                if(home.length()<101)
                {
                  p.executeUpdate();
                  
                  JOptionPane.showMessageDialog(this, "los datos se Guardaron exitosamente");
                
                  
                }
                
                else 
                {
                    JOptionPane.showMessageDialog(this, "ERROR");
                }
            }
            
            catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se pudo ingresar los dialogos");
             JOptionPane.showMessageDialog(null,e.getMessage());
                    
        }
        
        }
               
    
             public void nuevo()
             
             {
                         txtApellido.setText("");
                         txtNombre.setText("");
                         txtCalificacion.setText("");
                         txtCurso.setText("");
                     }
             
          
             public void editar () 
                     
             {
                 try {
                      
                     String SQL= "update alumnos set nombre=?, apeliido=?, materia=?, calificacion=? where idalumnos =?";
                     int filaSelect =jTableAlumnos.getSelectedRow();
                     String id = (String ) jTableAlumnos.getValueAt(filaSelect, 0);
                     
                     PreparedStatement p = cn.prepareStatement(SQL);
                     
                     p.setString(1, txtNombre.getText());
                     p.setString(2, txtApellido.getText());
                     p.setString(3, txtCurso.getText());
                     p.setString(4, txtCalificacion.getText());
                     p.setString(5, id);
                     p.execute();
                     
                    JOptionPane.showMessageDialog(null, "Registro Actualizado Exitosamente");
                 }
                 
                 catch (Exception e)
                 {
                     JOptionPane.showMessageDialog(null, "Error al registrar"+e.getMessage());
                 }
                 
             }
       
             public void MostrarDatos () {
                 String [] titulos = { "ID","Nombre","Apeliido","Materia","Calificacion"};
                 String [] registros = new String [7];
                 DefaultTableModel modelo = new  DefaultTableModel (null, titulos);
                 String sql = "select * from alumnos";
                 
                 try {
                     Statement st = cn.createStatement();
                     ResultSet rs =st.executeQuery(sql);
                     while (rs.next()){
                         registros [0]=rs.getString("idalumnos");
                         registros [1]=rs.getString("Nombre");
                         registros [2]=rs.getString("Apeliido");
                         registros [3]=rs.getString("materia");
                         registros [4]=rs.getString("Calificacion");
                         modelo.addRow(registros);
                         
                     }
                     jTableAlumnos.setModel(modelo);
                 }
                 catch  (Exception e) {
                     JOptionPane.showMessageDialog(null, "ERROR AL MOSTRAR DATOS"+e.getMessage());
                     
                 }
             }
       
             
             public void eliminar (){
                  if(JOptionPane.showConfirmDialog(this,"eliminar registro","confirmar",JOptionPane.YES_NO_OPTION)==0)
        
         
         {      
         
             String  sSql= "Delete from alumnos where idalumnos =?";
             
             
             int filaSelect =jTableAlumnos.getSelectedRow();
                     String id = (String ) jTableAlumnos.getValueAt(filaSelect, 0);
             try
             {
                 PreparedStatement p = cn.prepareStatement(sSql);
                 p.setString(1, id);
                 
                 p.executeUpdate();
                 
                 JOptionPane.showMessageDialog(null, "El registro ha sido eliminado exitosamente",
                         "Operación Exitosa", JOptionPane.INFORMATION_MESSAGE);
             }
             
            catch (Exception e)
                 {
                     JOptionPane.showMessageDialog(null, "Error al eliminar"+e.getMessage());
                 }
                 
             }
             }
             
             
             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMICRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMICRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMICRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMICRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMICRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAlumnos;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
